version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name codedeploycicd --s3-location s3://webservercicd20241031/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src